# Generated by Django 5.1.6 on 2025-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$EmxrnVE0NqZQxPLvEdSxel$6Ba+R3eU6gjTahn4vBaRwcw2xQiX3ZZINuUmlqZrmuw=', max_length=128),
        ),
    ]
