# Generated by Django 5.1.6 on 2025-03-11 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='travel_management.manager'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SWrkngG3rQfT9dagNIYYQN$kf1kM9OJqygQeQNlsb+7437Aqe1IK1Zoy9OSecRS5II=', max_length=128),
        ),
    ]
