# Generated by Django 5.1.6 on 2025-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0004_employee_manager_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$oSKNVoNcEw3nQ3VFenvOMj$B4o06pbsZOS9SC6QRiG5PtnHYIQYDesKEZT4qMzF0u8=', max_length=128),
        ),
    ]
