# Generated by Django 5.1.6 on 2025-03-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$6kiFxd9YHDJbW5mhkX3u9k$l8IHNFDEyUBPhPXqTj2rtkorV8+4LYVyMZXrxgyFMrY=', max_length=128),
        ),
    ]
