# Generated by Django 5.1.6 on 2025-03-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0006_customuser_status_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$NvlJNrPPCePiZY8eXu1T1F$uV/uaNJULPrAyVX98tKH7yqWrbekfRCh6fmMeiPFWyU=', max_length=128),
        ),
    ]
