# Generated by Django 5.1.6 on 2025-03-12 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0007_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$h5TIgKn2JiMGg0UXtGXU9S$o2QnmtfTKYP39k0wgzpj9pBc7hoIrbZABrD1iuPwyoc=', max_length=128),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', related_query_name='custom_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
