# Generated by Django 5.1.6 on 2025-03-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_management', '0009_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
